import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

function determinePaths() {
  const themePath = path.resolve(__dirname, "../src/config/theme.json");
  const outputPath = path.resolve(__dirname, "../src/styles/generated-theme.css");

  if (!fs.existsSync(themePath)) {
    throw new Error(`Could not find theme.json at: ${themePath}`);
  }

  return { themePath, outputPath };
}

const { themePath, outputPath } = determinePaths();

const toKebab = (str) => str.replace(/_/g, "-");

const findFont = (fontStr) =>
  fontStr.replace(/\+/g, " ").replace(/:[^:]+/g, "");

function addColorsToCss(cssLines, colors, prefix = "") {
  Object.entries(colors).forEach(([key, value]) => {
    const colorName = prefix
      ? `--color-${prefix}-${toKebab(key)}`
      : `--color-${toKebab(key)}`;
    cssLines.push(`  ${colorName}: ${value};`);
  });
}

function generateThemeCSS() {
  if (!fs.existsSync(themePath)) {
    throw new Error(`Theme configuration not found: ${themePath}`);
  }

  try {
    const themeConfig = JSON.parse(fs.readFileSync(themePath, "utf8"));

    if (!themeConfig.colors || !themeConfig.fonts) {
      throw new Error(
        "Invalid theme.json: missing 'colors' or 'fonts' section",
      );
    }

    const cssLines = [
      "/**",
      ' * Auto-generated from "src/config/theme.json"',
      " * DO NOT EDIT THIS FILE MANUALLY",
      " * Run: node scripts/themeGenerator.js",
      " */",
      "",
      "@theme {",
      "  /* === Colors === */",
    ];

    if (themeConfig.colors.default?.theme_color) {
      addColorsToCss(cssLines, themeConfig.colors.default.theme_color);
    }

    if (themeConfig.colors.default?.text_color) {
      addColorsToCss(cssLines, themeConfig.colors.default.text_color);
    }

    cssLines.push("", "  /* === Font Families === */");
    const fontFamily = themeConfig.fonts.font_family || {};
    Object.entries(fontFamily)
      .filter(([key]) => !key.includes("type"))
      .forEach(([key, font]) => {
        const fontFallback = fontFamily[`${key}_type`] || "sans-serif";
        const fontValue = `${findFont(font)}, ${fontFallback}`;
        cssLines.push(`  --font-${toKebab(key)}: ${fontValue};`);
      });

    cssLines.push("", "  /* === Font Sizes === */");
    const baseSize = Number(themeConfig.fonts.font_size?.base || 16);
    const scale = Number(themeConfig.fonts.font_size?.scale || 1.2);

    cssLines.push(`  --text-base: ${baseSize}px;`);
    cssLines.push(`  --text-base-sm: ${baseSize * 0.8}px;`);

    let currentSize = scale;
    for (let i = 6; i >= 1; i--) {
      cssLines.push(`  --text-h${i}: ${currentSize}rem;`);
      cssLines.push(`  --text-h${i}-sm: ${currentSize * 0.9}rem;`);
      currentSize *= scale;
    }

    cssLines.push("}");

    const outputDir = path.dirname(outputPath);
    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true });
    }

    fs.writeFileSync(outputPath, cssLines.join("\n") + "\n");
    console.log("✅ Theme CSS generated successfully at:", outputPath);
  } catch (error) {
    throw new Error(`Failed to generate theme CSS: ${error.message}`);
  }
}

try {
  generateThemeCSS();
} catch (error) {
  console.error("❌ Error:", error.message);
  process.exit(1);
}
